version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run test
      - npm run build:backend
  post_build:
    commands:
      - npm run provision:base
      - npm run build:backend
      - npm run deploy:backend
      - npm run build:frontend
      - npm run deploy:frontend
      - echo Deployed to...
      - npm run show:frontend-url
artifacts:
  files:
    - '**/*'
  base-directory: build