version: 0.2

phases:
  pre_build:
    commands:
      - npm -v
      - npm install
      - npm run test
  build:
    commands:
      - echo Build started on `date`
      - npm run build:backend
      - npm run build:frontend
  post_build:
    commands:
      - npm run deploy:backend
      - npm run deploy:frontend
      - echo Deployed to...
      - npm run show:frontend-url