---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  StagingBucketName:
    Type: String
  WebsiteBucketName:
    Type: String
  LambdaExecutionRole:
    Type: String

Resources:
  WineGuesserStagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StagingBucketName

  WineGuesserWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName

  WineGuesserLambdaExecutionRole:
    Type: AWS::IAM:Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      RoleName: !Ref LambdaExecutionRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts: AssumeRole

Outputs:
  WineGuesserWebsiteUrl:
    Description: Wine Guesser website URL.
    Value: !GetAtt WineGuesserWebsiteBucket.WebsiteUrl
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-website-url"

  WineGuesserLambdaExecutionRoleArn:
    Description: Wine Guesser lambda execution role arn.
    Value: !GetAtt WineGuesserLambdaExecutionRole.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-lambda-execution-role-arn"